<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mu Jia</title>

    <style>
        .module {
            height: 600px;
            background-color: #e0e0e0;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-top: 10px;
            font-size: 60px;
        }

        .module h1 {
            font-size: 100px;
        }

        .sub {
            justify-content: flex-start;
            height: 800px;
        }

        .module dl {
            width: 70%;
            margin-left: 20px;
        }


    </style>
</head>

<body>

<div class="module">
    <h1>农贸信息平台</h1>
</div>

<div class="module sub">
    <dl>
        <dt>项目简介</dt>
        <dd>
            <ul>
                <li>
                    这个项目是关于农贸相关的互联网项目，用户可以在平台上发布买卖信息。
                </li>
            </ul>
        </dd>

    </dl>

</div>


<div class="module sub">

    <dl>
        <dt>需求分析</dt>
        <dd>
            <ul>
                <li>
                    交易额较大
                </li>
                <li>
                    交易频率高
                </li>
                <li>
                    对信息的依赖性强。
                </li>
            </ul>

        </dd>

    </dl>
</div>


<div class="module sub">
    <dl>
        <dt>用户画像</dt>
        <dd>
            <ul>
                <li>
                    分布在广大农村，乡镇，城市。
                </li>
                <li>
                    职业为企业主，加工厂老板，贸易商，农场主，农民。
                </li>
            </ul>
        </dd>
    </dl>
</div>


<div class="module sub">
    <dl>
        <dt>产品运营</dt>
        <dd>
            <ul>
                <li>
                    垂直类的产业，特定的用户群，适合线下推广
                </li>
            </ul>
        </dd>
    </dl>
</div>


<div class="module sub">
    <dl>
        <dt>竞品分析</dt>
        <dd>
            <ul>
                <li>
                    中时通平台用户大约 40W，每一个品类（例如小麦）收费 4000 元，运营难度大。
                </li>

                <li>
                    天下粮仓比较注重传统的 PC 端页面，偏重于行情的分析，收费 8000 元，运营难度大。
                </li>
            </ul>
        </dd>
    </dl>
</div>


<div class="module sub">
    <dl>
        <dt>盈利分析</dt>
        <dd>
            <ul>
                <li>
                    特定的用户群，不希望有无关的信息，暂定为收费平台
                </li>

                <li>
                    用户量大，用户预计 40 W，收费暂定为 100 元，年预计营收 4000 W，年预计成本 200 W，年利润预计 3000 W
                </li>
            </ul>
        </dd>
    </dl>
</div>

</body>

</html>